name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./src/charp-intro-ptbr

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Deploy the binaries
      run: echo "Deployment in execution..."